[pytest]
markers =
    skip: пропуск теста
    xfail: ожидаемо тест упадет
    smoke: тесты для смоук-прогона
    regress: тесты для регресса

addopts =
;    --check-max-tb=100
    --alluredir=allure-results
